### ISSUE TITLE
gstd compilation error on ubuntu12.04

### ISSUE THREAD

**Issue by buchibabu** [RidgeRun/gstd#11]
hi i am getting following error while compiling gstd on ubuntu 12.04
VALAC  gst_client_vala.stamp
error: Package `gstreamer-video-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
i installed gstreamer1.0  and Vala 0.12.1 on my pc  
any help please...

**Comment by crmurillo** [comment]
Hi!

The package gstreamer-video-1.0 is provided by gstreamer-plugins-base, so probably you just need to install libgstreamer-plugins-base1.0-dev.

**Comment by michaelgruner** [comment]
This a no longer maintained version mainly for GStreamer **0.10**. Please check out [our Gstd for GStreamer 1.0](https://github.com/RidgeRun/gstd-1.x). 

Additionally, we are working on some documentation in our [project wiki page](https://developer.ridgerun.com/wiki/index.php?title=Gstd-1.0).
