### ISSUE TITLE
building with gstreamer 1.0 for ubuntu 14.04

### ISSUE THREAD

**Issue by snowmania** [RidgeRun/gstd#12]
Hello,

I'm trying to build gstreamer daemon for ubuntu trusty 14.04 following [this ](https://github.com/RidgeRun/gstd/wiki/Building-gstreamer-daemon#Ubuntu_host_PC)

Vala builds correctly but when I reach the make of gstreamer dameon I get the following error:

error: Package `gstreamer-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package`gstreamer-base-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `gstreamer-controller-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package`gstreamer-video-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories

And I doubled checked that gstreamer-1.0 is installed and up to date and the other packages (base controller and video) I get the answer that they are not found.

I have installed these: sudo apt-get install libdbus-1-dev libdbus-glib-1-dev libgstreamer1.0-dev libreadline-dev libgstreamer-plugins-base1.0-dev git libreadline-dev

Any idea is appreciated!
Claire

**Comment by michaelgruner** [comment]
This a no longer maintained version for GStreamer **0.10**. Please check out [our Gstd for GStreamer 1.0](https://github.com/RidgeRun/gstd-1.x). 

Additionally, we are working on some documentation in our [project wiki page](https://developer.ridgerun.com/wiki/index.php?title=Gstd-1.0).
