### ISSUE TITLE
Building for custom GST path

### ISSUE THREAD

**Issue by aplocher** [RidgeRun/gstd#13]
Hello, I have all my compiled GST stuff prefixed at /opt/gst (so /opt/gst/lib, /opt/gst/bin, etc)

How can I instruct the configure script for gstd to check there?

I've tried several things, see below:

`GST_LIBS=/opt/gst/lib/gstreamer-1.0 PKG_CONFIG_LIBDIR=/opt/gst/lib/gstreamer-1.0 ./configure --prefix=/opt/gst --libdir=/opt/gst/lib/gstreamer-1.0 --with-pkg-config-path=/opt/gst/lib/pkgconfig --with-gstreamer-version=1.0 --bindir=/opt/gst/bin`

And still I get 

```
checking for GST... no
configure: error: The requested gstreamer version 1.0 was not found

```

**Comment by michaelgruner** [comment]
This a no longer maintained version for GStreamer **0.10**. Please check out [our Gstd for GStreamer 1.0](https://github.com/RidgeRun/gstd-1.x). 

Additionally, we are working on some documentation in our [project wiki page](https://developer.ridgerun.com/wiki/index.php?title=Gstd-1.0).

**Comment by aplocher** [comment]
Oh thanks, I didn't realize this was for 0.10.  It doesn't seem indicated anywhere.

Thanks, will check out 1.0 version...
